########################################
#
#  IUPUI CSCI 503 -- Operating Systems
#
########################################

## Compiler, tools and options
cc      = gcc

## FILES
TARGET = shell

shell:
	cc -std=c99 -o shell shell.c

clean:
	rm -f $(OBJECTS) $(TARGET)
	rm -f *~ core